version: "3"
services:
  mariadb:
    image: "mariadb:10.5"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}

    volumes:
      - db:/var/lib/mysql
      - ./db/sakila.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - 3306:3306
  app:
    build: ./src/docker/
    ports:
      - ${APP_PORT}:${APP_PORT}
    links:
      - mariadb

volumes:
  db: {}