version: "3.7"
services:
  mariadb:
    image: "mariadb:10.9"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - ./db/sakila.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  app:
    build:
      context: ./src
      dockerfile: "docker/Dockerfile"
      args:
        - GO_VERSION=${GO_VERSION}
    links:
      - mariadb
    depends_on:
      - mariadb
    command: sh -c "/wait && /bin/air"
    volumes:
      - ./src/:/app
    environment:
      - WAIT_HOSTS=mariadb:${DATABASE_PORT}
      - WAIT_BEFORE=5
      - WAIT_HOSTS_TIMEOUT=30
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=10
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
volumes:
  db: {}